# change the followings to match your Github username and repo name
baseurl: "/carolines" # the name of your github repo
url: "https://carolines.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: Caroline S. Personal Website
description: Programming Portfolio

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Caroline S
author-bio: University of Delaware 
author-image: DSC_0159.JPG  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: false
  permalink: false
- text: Portfolio
  permalink: Portfolio

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: false
linkedin: https://www.linkedin.com/in/carolineelisesumner/
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: false

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
